### ISSUE TITLE
Issue with importing TFDV 0.21.2 on MacOS 10.12.6(Sierra)

### ISSUE THREAD

**Issue by KevsProjects** [tensorflow/data-validation#112]
I am running into the following error, trying both on PyCharm and a virtualenv when I am trying to import tensorflow_data_validation.

`Error importing tfx_bsl_extension.arrow.array_util. Some tfx_bsl functionalities are not availableError importing tfx_bsl_extension.arrow.table_util. Some tfx_bsl functionalities are not availableTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/__init__.py", line 27, in <module>
    from tensorflow_data_validation.api.validation_api import infer_schema
  File "/Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/api/validation_api.py", line 31, in <module>
    from tensorflow_data_validation.pywrap import pywrap_tensorflow_data_validation
  File "/Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/pywrap/pywrap_tensorflow_data_validation.py", line 28, in <module>
    _pywrap_tensorflow_data_validation = swig_import_helper()
  File "/Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/pywrap/pywrap_tensorflow_data_validation.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_data_validation', fp, pathname, description)
  File "/Users/ky/tfdvtest/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/ky/tfdvtest/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/ky/tfdvtest/lib/python3.7/site-packages/tensorflow_data_validation/pywrap/_pywrap_tensorflow_data_validation.so`

I have been using all the versions of tensorflow(2.1), apache-beam(2.17), and pyarrow(0.15.0) that are recommended as compatible. I am also using tfx-bsl(0.21.2). Has anyone run into this issue before?

**Comment by guoguolan1991** [comment]
do you solve this problem?

**Comment by guoguolan1991** [comment]
do you solve this problem? I  had the same problem as you

**Comment by caveness** [comment]
Sorry for the delay on this -- we're working on getting a new wheel for you to try. 

@guoguolan1991: Are you using Python 3.7 as well? Or a different Python version?

**Comment by guoguolan1991** [comment]
> Sorry for the delay on this -- we're working on getting a new wheel for you to try.
> 
> @guoguolan1991: Are you using Python 3.7 as well? Or a different Python version?

Thanks for your reply.

my python version is 3.6, mac os  is 10.12.6.
I try to build tfdv from source, and finally install successful,
then import tensorflow_data_validation as tfdv without error.

1. Symbol not found: ____chkstk_darwin , because this is only support by macos 10.15. so I decide to build tfdv from source. you can follow the instruction by the link:https://www.tensorflow.org/tfx/data_validation/install, I use bazel(version:0.24.1, version too high or too low may not work) to build the source
2.after step 1, I successful install tfdv, and import without error, but I had another similar  problem of tfx-bsl.  so I install tfx-bsl from source, you can follow the instruction by the link:https://pypi.org/project/tfx-bsl/

after two step below, I solve the problem

**Comment by caveness** [comment]
Here are updated MacOS Python3.7 and Python 3.6 wheels to try out. (I had to rename the file to have a .zip extension in order to be able to attach the file here, but you should be able to rename it back to .whl.) Please let me know if this works for you. Thanks!

[tensorflow_data_validation-0.22.0.dev0-cp36-cp36m-macosx_10_9_x86_64.zip](https://github.com/tensorflow/data-validation/files/4372625/tensorflow_data_validation-0.22.0.dev0-cp36-cp36m-macosx_10_9_x86_64.zip)
[tensorflow_data_validation-0.22.0.dev0-cp37-cp37m-macosx_10_9_x86_64.zip](https://github.com/tensorflow/data-validation/files/4372554/tensorflow_data_validation-0.22.0.dev0-cp37-cp37m-macosx_10_9_x86_64.zip)

**Comment by smathalikunnel** [comment]
Hi,

Is there any solution yet. I am getting the same error running on AI Platform Notebook instance (tensorflow 2.1 or 2.2). This suggests that this might not be a MACOS issue?

**Comment by smathalikunnel** [comment]
Issue fixed by upgrading to v0.22.0

!pip install 'tensorflow-data-validation==0.22.0' --force-reinstall

**Comment by caveness** [comment]
Closing as upgrading TFDV version appears to resolve the issue.
