### ISSUE TITLE
Is google cloud *required* to run tfdv on cluster setup ?

### ISSUE THREAD

**Issue by aviatesk** [tensorflow/data-validation#150]
Hi, I would like to clarify whether if we can run this package on other cloud computing platforms like AWS.

README says

> Apache Beam is required; it's the way that efficient distributed computation is supported. By default, Apache Beam runs in local mode but can also run in distributed mode using Google Cloud Dataflow and other Apache Beam runners.

Does this mean, we _need_ to use Dataflow to run tfdv in distributed mode ? Or, can we actually use the other Beam runners like Spark runner not via Dataflow interface ?
(I'm yet not familiar with Beam and I'm not sure what [the dependency of `apache-beam[gcp]`](https://github.com/tensorflow/data-validation/blob/5851c451c80439ec054b3285c84f8b66b9a3a9c1/setup.py#L181) means)

/cc @rmothukuru @brills could you please clarify this ?
/cc @xjj59307 friendly ping because you tried to run tfdv on aws with Direct runner (#133 )

**Comment by brills** [comment]
We only tested TFDV w/ the DataFlow runner and the Direct runner (i.e. local mode). There are other runners and nothing in TFDV's API assumes a certain runner so you can definitely try. But because each runner has its own capabilities, we don't guarantee anything beyond the DataFlow runner and the Direct runner.
