### ISSUE TITLE
How to treat integers as categorical features?

### ISSUE THREAD

**Issue by kennysong** [tensorflow/data-validation#153]
It seems that TFDV treats integers as numeric features when computing and visualizing statistics.

This leads to some weird side effects for a categorical integer feature. For example, for a binary {0, 1} feature:

- Histograms, instead of having two values, are bucketized as a continuous range, e.g. [0.0, 0.1], [0.1, 0.2], ..., [0.9, 1.0].
- Skew detection cannot compute the L-infinity norm (it's set to zero), only the JS divergence 

How do I treat an integer as a categorical feature?

**Comment by caveness** [comment]
Hi -- To treat an integer as a categorical feature, set [is_categorical](https://github.com/tensorflow/metadata/blob/7d6df7bcc240ea8cb258669784142a1a1f8b7b9c/tensorflow_metadata/proto/v0/schema.proto#L469) to true in the schema.

**Comment by kennysong** [comment]
Thanks @caveness! That fixes the histogram and skew detection.

But I think there's a bug when validating statistics with a categorical int feature – it (incorrectly?) raises an `DOMAIN_INVALID_FOR_TYPE` anomaly.

[Here's a short notebook](https://colab.research.google.com/drive/1qhjsHddYfJqjpZaDWoLqBR_pF8Rgn4In?usp=sharing) that replicates this.

**Comment by gaikwadrahul8** [comment]
@kennysong 

We have updated our TFDV official documentation [here](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv) with new data validation functions so I would request you to please try with new functions instead of `tfdv.validate_instance()` to find anomalies in the discrete integer categorical features and please check whether have we taken care that issue in our latest version of TFDV and as you suggested one workaround [here](https://github.com/tensorflow/data-validation/issues/131) so it's working fine and even I reproduced that same code of user [here](https://colab.sandbox.google.com/gist/gaikwadrahul8/deb801c31c55254fa3f412e5e2a0b6bf/tfdv-categorical-int-bug.ipynb) with your same approach.

If you need any further assistance please let us know ? or if your suggested workaround working fine then could you please close this issue ?

Thank you!
