### ISSUE TITLE
Infer multivalent features with tfdv from pandas dataframe does not work

### ISSUE THREAD

**Issue by ppmt-github** [tensorflow/data-validation#208]
I want to infer a schema with tensorflow data validation (tfdv) based on a pandas dataframe of the training data. The dataframe contains a column with a multivalent feature, where multiple values (or None) of the feature can be present at the same time. The goal is to used the inferred schema and its domain to find anomalies in serving data (e.g., a previously unseen value of the multivalent feature)

Given the following dataframe:
```
df = pd.DataFrame([{'feat_1': 13, 'feat_2': 'AA, BB', 'feat_3': 'X'},
                   {'feat_1': 7, 'feat_2': 'AA', 'feat_3': 'Y'},
                   {'feat_1': 7, 'feat_2': None, 'feat_3': None}])
```
inferring and displaying the schema results in:

![image](https://user-images.githubusercontent.com/60098436/155998753-28d3c424-4456-4856-aff3-a52b9088ef37.png)

Thus, tfdv treats the 'feat_2' values as a single string instead of splitting them at the ',' to produce a domain of 'AA', 'BB':

![image](https://user-images.githubusercontent.com/60098436/155998785-d944d887-98a1-49d0-ac97-11f28c6a26e8.png)

If if save the values of feature as e.g., `['AA', 'BB']`, the schema inference throws an error:

`ArrowTypeError: ("Expected bytes, got a 'list' object", 'Conversion failed for column feat_2 with type object')`

Is there any way to achieve this with tfdv?

**Comment by caveness** [comment]
Hi -- TFDV does not currently support generating statistics from a pandas DataFrame with columns containing multivalent features. Only columns with primitive types are supported. Because schema inference is based on stats, that means we don't support schema inference on such data either. We've updated the help for `generate_statistics_from_dataframe` to note this limitation. Should we support multivalent features in this function in the future, we will update that documentation accordingly.
