### ISSUE TITLE
hot key issue

### ISSUE THREAD

**Issue by zexuan-zhou** [tensorflow/data-validation#230]
Hi,

Cool thanks.
I’m using the [GenerateStatistics](https://github.com/tensorflow/data-validation/blob/38fe41e82355954891077d0a4950e4a1e2d74485/tensorflow_data_validation/api/stats_api.py#L59) API and I’m running into hot key issues

`GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators[0]/CombinePerKey(PostCombineFn)/GroupByKey/Read+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators[0]/CombinePerKey(PostCombineFn)/Combine+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/RunCombinerStatsGenerators[0]/CombinePerKey(PostCombineFn)/Combine/Extract+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/FlattenFeatureStatistics/OutputIdentity+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/AddSliceKeyToStatsProto+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/ToList/ToList/KeyWithVoid+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/ToList/ToList/CombinePerKey/GroupByKey+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/ToList/ToList/CombinePerKey/Combine/Partial+GenerateStatistics(EVALUATION)/RunStatsGenerators/GenerateSlicedStatisticsImpl/ToList/ToList/CombinePerKey/GroupByKey/Write`

I wonder if tensorflow data validation has some functionalities to mitigate this. I looked at [StatsOptions](https://github.com/tensorflow/data-validation/blob/b98fbadcf148d32aedc9261ce608bd6012c5f025/tensorflow_data_validation/statistics/stats_options.py#L52) but I do not see any hot key related parameter

Unfortunately I do not have a good example of code snippet for reproducible result. So this is a general question

Thanks

**Comment by zexuan-zhou** [comment]
Thank you.

Yes I have ~1000 features, and the code to generate statistics is just a one liner

```
import tensorflow_data_validation as tfdv
...

... tfdv.GenerateStatistics(...) ...
```
and I think GenerateStatistics calls [GenerateStatisticsImpl](https://github.com/tensorflow/data-validation/blob/38fe41e82355954891077d0a4950e4a1e2d74485/tensorflow_data_validation/api/stats_api.py#L100) if by slicing that's what you mean.

As for experimental_num_feature_partitions, thanks I'll give it a try

**Comment by zexuan-zhou** [comment]
`experimental_num_feature_partitions` seems help a lot. But then I ran into another issue where html overview generated by `tfdv.utils.display_util.get_statistics_html` is empty. Any idea what could go wrong or what need to be changed to make it work?

sudo code is like this
```
stats = some_data |  "SummaryStats" >> tfdv.GenerateStatistics(...)  # experimental_num_feature_partitions is used here
html = stats | "StatsHtml" >> beam.Map(tfdv.utils.display_util.get_statistics_html, lhs_name="DataStats")
html | "WriteHtmlStats" >> beam.io.WriteToText(...)
```

Thank you

**Comment by gaikwadrahul8** [comment]
Hi, @zexuan-zhou 

Apologies for the delay and as @zwestrick mentioned above option `experimental_num_feature_partitions` If > 1, partitions computations by supported generators to act on this many bundles of features. For best results this should be set to at least several times less than the number of features in a dataset, and never more than the available beam parallelism and to combine the result there is option of `experimental_result_partitions` is The number of feature partitions to combine output DatasetFeatureStatisticsLists into. If set to 1 (default) output is globally combined. If set to value greater than one, up to that many shards are returned, each containing a subset of features.

You can refer our complete `GenerateStatistics` code and we are using `hot_key_fanout ` [here](https://github.com/tensorflow/data-validation/blob/22d3c62faf7776879848e00c6c0c308d84bfbc85/tensorflow_data_validation/statistics/stats_impl.py#L278) and you can also refer Options for generating statistics official documentation [here](https://www.tensorflow.org/tfx/data_validation/api_docs/python/tfdv/StatsOptions), I hope it will help you to resolve your issue

Could you please confirm if this issue is resolved for you? Please feel free to close the issue if it is resolved ? 

If issue still persists please let us know ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @zexuan-zhou 

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update

Thank you!
