### ISSUE TITLE
tf.SequenceExample support

### ISSUE THREAD

**Issue by martin-laurent** [tensorflow/data-validation#45]
Does TFDV support reading tf.SequenceExample from TFRecords, inferring a schema over them and compute statistics from them?

**Comment by caveness** [comment]
@martin-laurent TFDV does not currently support tf.SequenceExamples, but we plan to add such support in the future.

**Comment by ymodak** [comment]
Closing this issue since @caveness's explanation solves it. Feel free to reopen if have any follow up questions. Thanks!

**Comment by TimSmole** [comment]
Any news on this topic? Or perhaps any estimate on when we can expect this feature? Thanks!

**Comment by gaikwadrahul8** [comment]
@martin-laurent 

TFDV now supports SequenceExample from TFRecords. Please check these 02 references [1 ](https://github.com/tensorflow/data-validation/blob/master/tensorflow_data_validation/integration_tests/sequence_example_e2e_test.py)and [2](https://www.tensorflow.org/tfx/tfx_bsl/api_docs/python/tfx_bsl/public/tfxio/TFSequenceExampleRecord) and let us know you're looking the exact Feature in TFDV Library ?

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @martin-laurent 

We have updated our official documentation w.r.t `SequenceExample` [here](https://www.tensorflow.org/api_docs/python/tf/train/SequenceExample) and also check these comments [[1]](https://github.com/tensorflow/data-validation/issues/67#issuecomment-815081429) , [[2]](https://github.com/tensorflow/tfx/issues/4714#issuecomment-1351368450)

Closing this issue due to lack of recent activity for couple of weeks. Please feel free to reopen the issue or post comments, if you need any further assistance or update

Thank you!
