### ISSUE TITLE
pip install tensorflow-data-validation fails on OS X El Capitan (10.11.6)

### ISSUE THREAD

**Issue by wjarek2** [tensorflow/data-validation#7]
pip  install tensorflow-data-validation
Collecting tensorflow-data-validation
  Could not find a version that satisfies the requirement tensorflow-data-validation (from versions: )
No matching distribution found for tensorflow-data-validation

**Comment by ArvinSiChuan** [comment]
I can't install on Ubuntu 16 either.

**Comment by paulgc** [comment]
Can you share the following information to help us debug the issue:
- Your Python version and pip version
- What error do you get when installing through pip?
- Do you have tensorflow installed?

**Comment by ArvinSiChuan** [comment]
@paulgc  
I'm using virtualenv, This is my env info:  
```
Python 3.5.2
pip 18.0 from /home/jovyan/keras-py3/lib/python3.5/site-packages/pip (python 3.5)
Tensorflow installed with version 1.10.0
```

**Comment by paulgc** [comment]
@ArvinSiChuan 
Currently, we only support Python 2.7 as we depend on Apache Beam, which is not compatible with Python 3 yet. But we plan to add Python 3 support very soon, as [Apache Beam is almost Python 3 ready](https://issues.apache.org/jira/browse/BEAM-1251).

**Comment by ArvinSiChuan** [comment]
@paulgc So that makes sense. But I have a suggestion that you declare the python version in  either `Prerequisites` or `Supported platforms` of your README file. And, I'd like to wait for the coming of py3 support.

**Comment by Efaq** [comment]
Hi

**Even using python 2.7**, I get the error reported above, on Windows 10. It seems to be an issue with tensorflow-data-validation in pip because I am able to install tensorflow-transform and tensorflow-model-analysis, which have the same kind of dependence on python 2.

That is, this works:

`pip2.7 install tensorflow-model-analysis`

And this too:

`pip2.7 install tensorflow-transform`

But not this:

`pip2.7 install tensorflow-data-validation`

My version:

`pip2.7 --version`

and I get:

`pip 18.1 from (...)\site-packages\pip (python 2.7)`

**Comment by paulgc** [comment]
@Efaq 
Currently we release PyPI packages only for MacOS and Ubuntu.

**Comment by Efaq** [comment]
@paulgc Ok, thank you! I have indeed installed everything successfully in Ubuntu.

**Comment by brianmartin** [comment]
@paulgc Seems this should be closed or retitled to "Support and publish for Windows"?

**Comment by harshini-gadige** [comment]
@paulgc  Can this be closed for now ?
